model:
  name: MOs
  table_name: m_os
  fields:
    id:
      name: id
      type: Integer
      required: true
      primary_key: true
      label: ID
    name:
      name: name
      type: String(50)
      required: true
      default: null
      label: OS名
    comment:
      name: comment
      type: String(200)
      required: true
      default: null
      label: コメント
    delflg:
      name: delflg
      type: Integer
      required: false
      default: 0
      label: 削除フラグ
