master:
  title: "マスター管理"

  quick_nav:
    - name: "ユーザー管理"
      path: "/master/m_users"
      icon: "fas fa-users"
      color: "bg-gradient-to-r from-blue-500 to-blue-600"
    - name: "作業管理"
      path: "/master/t_work"
      icon: "fas fa-tasks"
      color: "bg-gradient-to-r from-green-500 to-green-600"
    - name: "顧客管理"
      path: "/master/m_customers"
      icon: "fas fa-building"
      color: "bg-gradient-to-r from-purple-500 to-purple-600"
    - name: "フォルダ管理"
      path: "/master/m_folder"
      icon: "fas fa-folder"
      color: "bg-gradient-to-r from-indigo-500 to-indigo-600"
    - name: "作業サブ管理"
      path: "/master/t_work_sub"
      icon: "fas fa-list-ul"
      color: "bg-gradient-to-r from-red-500 to-red-600"
    - name: "OS管理"
      path: "/master/m_os"
      icon: "fas fa-laptop"
      color: "bg-gradient-to-r from-yellow-500 to-yellow-600"
    - name: "バージョン管理"
      path: "/master/m_version"
      icon: "fas fa-code-branch"
      color: "bg-gradient-to-r from-pink-500 to-pink-600"
    - name: "作業分類管理"
      path: "/master/m_workclass"
      icon: "fas fa-tags"
      color: "bg-gradient-to-r from-teal-500 to-teal-600"
    - name: "ログ管理"
      path: "/master/t_logs"
      icon: "fas fa-history"
      color: "bg-gradient-to-r from-gray-500 to-gray-600"