version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  # 修改为你自己的 root 密码
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      # PMA_USER: root
      # PMA_PASSWORD: rootpass  # 和上面的 root 密码一致
    ports:
      - "3001:80"
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  mariadb_data:
